run:
  dir: ${paths.base_output_dir}/${now:%Y-%m-%d}_${now:%H-%M-%S}

job:
  name: app  # Default job name for log file (${job.name}.log)

job_logging:
  handlers: [console, file]  # Available handlers: console, file
  root:
    level: INFO  # Available: TRACE, DEBUG, INFO, WARN, ERROR, FATAL
